# Generated by Django 4.2.1 on 2023-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('login', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_access', models.IntegerField()),
                ('access_level', models.IntegerField()),
                ('last_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('last_server', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('bonus_expire', models.IntegerField()),
                ('ban_expire', models.IntegerField()),
                ('allow_ip', models.CharField(max_length=255)),
                ('allow_hwid', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('phone_nubmer', models.BigIntegerField()),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
    ]
