# Generated by Django 4.2.1 on 2023-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('access_level', models.IntegerField(default=0)),
                ('last_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('last_server', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('bonus_expire', models.IntegerField(default=0)),
                ('ban_expire', models.IntegerField(default=0)),
                ('allow_ip', models.CharField(default='', max_length=255)),
                ('allow_hwid', models.CharField(default='', max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('phone_number', models.BigIntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
    ]
